# This file is automatically generated, and it is not recommended to change it
# Path: api/api_arpc.py
# Generated at [Sat Jul 23 13:20:11 2022]

import arpc


class RequestV1(arpc.Param):
    """
    This class is a Param class for arpc.
    """
    def __init__(self, user_id=0):
        self.user_id = user_id


class ResponseV1(arpc.Param):
    """
    This class is a Param class for arpc.
    """
    def __init__(self, user_id=0, username=""):
        self.user_id = user_id
        self.username = username
